[package]
name = "btc-toolkit"
version = "0.1.0"
edition = "2024"
description = "GUI tool for scanning local network for BTC ASIC Miners"
authors = ["Daniel Sokil <dtechtours@gmail.com>"]

[dependencies]
iced = "0.13"
mimalloc = { version = "0.1", features = ["secure"] }
asic-rs = { git = "https://github.com/b-rowan/asic-rs.git" }
